/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    media: Media;
    pages: Page;
    courses: Course;
    directions: Direction;
    levels: Level;
    formats: Format;
    galleries: Gallery;
    forms: Form;
    'form-requests': FormRequest;
    reviews: Review;
    comments: Comment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    directions: DirectionsSelect<false> | DirectionsSelect<true>;
    levels: LevelsSelect<false> | LevelsSelect<true>;
    formats: FormatsSelect<false> | FormatsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-requests': FormRequestsSelect<false> | FormRequestsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  username?: string | null;
  role: 'superAdmin' | 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username?: string | null;
  isApproved?: boolean | null;
  tabText_1?: string | null;
  tabText_2?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  sections?:
    | (
        | {
            title?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'service';
          }
        | {
            title?: string | null;
            description?: string | null;
            leftText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            rightText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'schedule';
          }
        | {
            title?: string | null;
            description?: string | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews';
          }
        | {
            title?: string | null;
            description?: string | null;
            form?: (number | null) | Form;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'request';
          }
        | {
            title?: string | null;
            description?: string | null;
            gallery?: (number | null) | Gallery;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    canonicalUrl?: string | null;
    metaRobots?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    preventIndexing?: boolean | null;
    metaViewport?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogUrl?: string | null;
    ogType?: string | null;
    twitterCard?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    structuredData?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title?: string | null;
  description?: string | null;
  submitUrl?: string | null;
  successMessage?: string | null;
  errorMessage?: string | null;
  fields?:
    | (
        | {
            label?: string | null;
            name: string;
            placeholder?: string | null;
            isRequired?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formTextarea';
          }
        | {
            label?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formSubmit';
          }
        | {
            label?: string | null;
            name: string;
            placeholder?: string | null;
            isRequired?: boolean | null;
            options?:
              | {
                  label?: string | null;
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formSelect';
          }
        | {
            label?: string | null;
            name: string;
            placeholder?: string | null;
            type?: ('text' | 'email') | null;
            isRequired?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formInput';
          }
        | {
            label?: string | null;
            name: string;
            type?: ('checkbox' | 'radio') | null;
            items?:
              | {
                  title?: string | null;
                  value: string;
                  isChecked?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formCheckboxes';
          }
        | {
            label?: string | null;
            name: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formAgree';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title?: string | null;
  description?: string | null;
  images?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price?: number | null;
  duration?: string | null;
  direction?: (number | null) | Direction;
  level?: (number | null) | Level;
  formats?: (number | Format)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    canonicalUrl?: string | null;
    metaRobots?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    preventIndexing?: boolean | null;
    metaViewport?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogUrl?: string | null;
    ogType?: string | null;
    twitterCard?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    structuredData?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions".
 */
export interface Direction {
  id: number;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "levels".
 */
export interface Level {
  id: number;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formats".
 */
export interface Format {
  id: number;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-requests".
 */
export interface FormRequest {
  id: number;
  formTitle?: string | null;
  formData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  title?: string | null;
  rating?: number | null;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isApproved?: boolean | null;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  title?: string | null;
  text?: string | null;
  isApproved?: boolean | null;
  user?: (number | null) | User;
  course?: (number | null) | Course;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'directions';
        value: number | Direction;
      } | null)
    | ({
        relationTo: 'levels';
        value: number | Level;
      } | null)
    | ({
        relationTo: 'formats';
        value: number | Format;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-requests';
        value: number | FormRequest;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  username?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  isApproved?: T;
  tabText_1?: T;
  tabText_2?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        service?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        schedule?:
          | T
          | {
              title?: T;
              description?: T;
              leftText?: T;
              rightText?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              title?: T;
              description?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        request?:
          | T
          | {
              title?: T;
              description?: T;
              form?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              description?: T;
              gallery?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              image?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        metaRobots?: T;
        preventIndexing?: T;
        metaViewport?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogUrl?: T;
        ogType?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        structuredData?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  image?: T;
  text?: T;
  price?: T;
  duration?: T;
  direction?: T;
  level?: T;
  formats?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        metaRobots?: T;
        preventIndexing?: T;
        metaViewport?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogUrl?: T;
        ogType?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        structuredData?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions_select".
 */
export interface DirectionsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "levels_select".
 */
export interface LevelsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formats_select".
 */
export interface FormatsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  submitUrl?: T;
  successMessage?: T;
  errorMessage?: T;
  fields?:
    | T
    | {
        formTextarea?:
          | T
          | {
              label?: T;
              name?: T;
              placeholder?: T;
              isRequired?: T;
              id?: T;
              blockName?: T;
            };
        formSubmit?:
          | T
          | {
              label?: T;
              id?: T;
              blockName?: T;
            };
        formSelect?:
          | T
          | {
              label?: T;
              name?: T;
              placeholder?: T;
              isRequired?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        formInput?:
          | T
          | {
              label?: T;
              name?: T;
              placeholder?: T;
              type?: T;
              isRequired?: T;
              id?: T;
              blockName?: T;
            };
        formCheckboxes?:
          | T
          | {
              label?: T;
              name?: T;
              type?: T;
              items?:
                | T
                | {
                    title?: T;
                    value?: T;
                    isChecked?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        formAgree?:
          | T
          | {
              label?: T;
              name?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-requests_select".
 */
export interface FormRequestsSelect<T extends boolean = true> {
  formTitle?: T;
  formData?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  rating?: T;
  text?: T;
  isApproved?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  isApproved?: T;
  user?: T;
  course?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  title?: string | null;
  logo?: (number | null) | Media;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  title?: string | null;
  logo?: (number | null) | Media;
  topText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bottomText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyright?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  title?: string | null;
  description?: string | null;
  sections?:
    | (
        | {
            title?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'service';
          }
        | {
            title?: string | null;
            description?: string | null;
            leftText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            rightText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'schedule';
          }
        | {
            title?: string | null;
            description?: string | null;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews';
          }
        | {
            title?: string | null;
            description?: string | null;
            form?: (number | null) | Form;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'request';
          }
        | {
            title?: string | null;
            description?: string | null;
            gallery?: (number | null) | Gallery;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title?: string | null;
            description?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    canonicalUrl?: string | null;
    metaRobots?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    preventIndexing?: boolean | null;
    metaViewport?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    ogUrl?: string | null;
    ogType?: string | null;
    twitterCard?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    structuredData?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  topText?: T;
  bottomText?: T;
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        service?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        schedule?:
          | T
          | {
              title?: T;
              description?: T;
              leftText?: T;
              rightText?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              title?: T;
              description?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        request?:
          | T
          | {
              title?: T;
              description?: T;
              form?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              description?: T;
              gallery?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              description?: T;
              text?: T;
              image?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        metaRobots?: T;
        preventIndexing?: T;
        metaViewport?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogUrl?: T;
        ogType?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        structuredData?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}